{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.name }}-frontend"
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.networkPolicy.frontend.app }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - {}

  egress:
    # 1) Hacia backend-api (u otros internos)
    - to:
        {{- range .Values.networkPolicy.frontend.allowedTo }}
        - podSelector:
            matchLabels:
              app: {{ .app }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.frontend.allowedTo }}
        - protocol: TCP
          port: {{ .port }}
        {{- end }}

    # 2) Hacia Internet (80/443) solo si allowInternet = true
    {{- if .Values.networkPolicy.frontend.allowInternet }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}