{{- if and .Values.route.enabled .Values.service.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  {{- if .Values.route.host }}
  host: "{{ .Values.route.host }}"
  {{- end }}
  to:
    kind: Service
    name: "{{ .Values.route.serviceName | default .Values.name }}"
    weight: 100
  port:
    targetPort: {{ .Values.route.targetPort | default .Values.service.port }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: "{{ .Values.route.tls.termination }}"
    insecureEdgeTerminationPolicy: "{{ .Values.route.tls.insecureEdgeTerminationPolicy }}"
  {{- end }}
{{- end }}