{{- if and .Values.secret.enabled .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret"
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}